#!/usr/bin/env python3
"""
generate_newsletter.py — Render the rolling NEWSLETTER.md (one section per topic).

Each topic section presents the **latest research** (top findings by composite in
the current window) and the **emerging trends** (from trends.json), as a scannable
issue for expert readers. It's rolling: regenerated every scan, always reflecting
the current window. Run after generate_site.py + trends.py.

Usage:
    python scripts/generate_newsletter.py
"""

from __future__ import annotations

from datetime import UTC, datetime

import common as c

TOP_RESEARCH = 6  # latest findings shown per topic
TOP_TRENDS = 3  # emerging themes shown per topic


def composite_of(entry: dict, conf: c.Config) -> float:
    scores = entry.get("scores") or {}
    if "composite" in scores:
        return float(scores["composite"])
    live = dict(scores)
    live["newness"] = c.newness_score(c.best_date(entry) or "", conf.half_life_days)
    return c.composite_score(live, conf.weights)


def research_block(entry: dict, conf: c.Config) -> list[str]:
    take = entry.get("takeaway") or entry.get("summary") or entry.get("threat") or ""
    src = entry.get("source_name", "source")
    line = [
        f"- **[{entry.get('title','')}]({entry.get('source_url','')})** "
        f"· _{src}_ · composite {composite_of(entry, conf)}"
    ]
    if take:
        line.append(f"  {c.clean_summary(take, 220)}")
    act = entry.get("actionable")
    if isinstance(act, dict) and act.get("title"):
        line.append(f"  → **Do:** ({act.get('type','')}) {act.get('title')}")
    return line


def topic_section(topic: str, conf: c.Config, trends: list[dict]) -> list[str]:
    meta = c.TOPICS[topic]
    curated = [e for e in c.load_pool(topic)["entries"] if c.is_curated(e, conf)]
    entries = sorted(curated, key=lambda e: -composite_of(e, conf))
    out = [f"## {meta['name']}", "", f"_{meta['blurb']}_", ""]

    out += ["**🔬 Latest research**", ""]
    if entries:
        for e in entries[:TOP_RESEARCH]:
            out += research_block(e, conf)
    else:
        out.append("- _Nothing new in the current window._")
    out.append("")

    out += ["**📈 Emerging trends**", ""]
    if trends:
        for t in trends[:TOP_TRENDS]:
            arrow = "🔺 rising" if t["recent"] else "watching"
            out.append(
                f"- **{t['tag']}** ({arrow}) — {t['count']} findings from "
                f"{t['sources']} sources since {t['first_seen']}."
            )
    else:
        out.append("- _No theme has crossed the threshold yet._")
    out += ["", f"[→ Full {meta['name']} database]({topic}/README.md)", "", "---", ""]
    return out


def build(conf: c.Config, now: str) -> str:
    all_trends = c.load_json(c.DATA_DIR / "trends.json", default={}) or {}
    total = sum(len(c.load_pool(t)["entries"]) for t in c.TOPICS)
    out = [
        f"# 📰 Security & AI Research — Daily Snapshot ({now})",
        "",
        f"> A daily-refreshed digest of the most teachable, **vetted** security and AI research "
        f"from the last {conf.max_age_days} days, curated and source-cited. Three tracks: "
        "AI Security, Product Security, AI Research.",
        "",
        f"{total} vetted findings in window · [← home](README.md) · "
        "[full trends](TRENDS.md) · [all learnings](LEARNINGS.md)",
        "",
        "---",
        "",
    ]
    for topic in c.TOPICS:
        out += topic_section(topic, conf, all_trends.get(topic, []))
    out += [
        "_Every finding links its original source. Curated by the AwesomeSecurityResearch "
        "analyzer; low-confidence or unverified items are held for review and not shown here._",
        "",
        f"<sub>Generated by scripts/generate_newsletter.py on {now}.</sub>",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    conf = c.load_config()
    now = datetime.now(UTC).strftime("%Y-%m-%d")
    (c.ROOT / "NEWSLETTER.md").write_text(build(conf, now), encoding="utf-8")
    print("Wrote NEWSLETTER.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
