#!/usr/bin/env python3
"""
generate_review.py — Render REVIEW.md, the human triage queue.

Findings that are in the current window but NOT vetted — flagged `needs_review`
(low confidence / novelty / relevance) or below the composite floor — are listed
here per topic with the reason. They stay in the pool (and can be promoted); they
just don't appear in the topic pages or newsletter until a human vets them.

Promote an item by fixing/raising its scores or setting `needs_review: false`
(above the floor) in its topic pool file, then regenerate.

Usage:
    python scripts/generate_review.py
"""

from __future__ import annotations

from datetime import UTC, datetime

import common as c


def review_items(topic: str, conf: c.Config) -> list[dict]:
    return [e for e in c.load_pool(topic)["entries"] if not c.is_curated(e, conf)]


def build(conf: c.Config, now: str) -> str:
    out = [
        "# 🔍 Review Queue",
        "",
        f"> Findings in the last {conf.max_age_days} days that are **not yet vetted** — held "
        "out of the topic pages and newsletter. Flagged for low confidence/novelty/relevance, or "
        f"below the composite floor ({conf.curation.get('min_composite', 0)}). Nothing here is "
        "deleted; promote an item by raising its scores or clearing `needs_review`, then regenerate.",
        "",
        f"_Updated {now}._",
        "",
    ]
    total = 0
    for topic, meta in c.TOPICS.items():
        items = sorted(review_items(topic, conf), key=lambda e: -c.entry_composite(e, conf))
        total += len(items)
        out += [f"## {meta['name']} ({len(items)})", ""]
        if not items:
            out += ["_Nothing awaiting review._", ""]
            continue
        for e in items:
            take = e.get("takeaway") or e.get("summary") or e.get("threat") or ""
            out.append(
                f"- **[{e.get('title','')}]({e.get('source_url','')})** "
                f"· composite {c.entry_composite(e, conf)} · _{c.review_reason(e, conf)}_"
            )
            if take:
                out.append(f"  {c.clean_summary(take, 180)}")
        out.append("")
    out += [
        "---",
        "",
        f"<sub>Generated by scripts/generate_review.py on {now}. "
        f"{total} item(s) awaiting review.</sub>",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    conf = c.load_config()
    now = datetime.now(UTC).strftime("%Y-%m-%d")
    (c.ROOT / "REVIEW.md").write_text(build(conf, now), encoding="utf-8")
    n = sum(len(review_items(t, conf)) for t in c.TOPICS)
    print(f"Wrote REVIEW.md ({n} item(s) awaiting review).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
