#!/usr/bin/env python3
"""
trends.py — Detect emerging themes per topic and render TRENDS.md.

Clusters entries (live pool + recent archive) by their `tags` within each topic,
and surfaces tags that (a) have enough members from (b) enough distinct sources,
weighting recent activity so a *rising* theme ranks above a stale one. This is
how we spot a wave early — e.g. a surge of agent-security tooling — without
embeddings. Writes data/trends.json (machine) + TRENDS.md (human).

Usage:
    python scripts/trends.py
"""

from __future__ import annotations

from collections import defaultdict
from datetime import UTC, datetime

import common as c

MIN_MEMBERS = 2  # a theme needs at least this many findings
MIN_SOURCES = 2  # …from at least this many distinct sources
RECENT_WEIGHT = 2.0  # in-window members count this much more than archived ones


def entries_for_topic(topic: str) -> list[dict]:
    live = c.load_pool(topic)["entries"]
    archive = [
        e for e in (c.load_json(c.ARCHIVE_FILE, default=[]) or []) if e.get("topic") == topic
    ]
    seen, out = set(), []
    for e in live + archive:
        key = e.get("id") or e.get("source_url")
        if key not in seen:
            seen.add(key)
            out.append(e)
    return out


def source_key(e: dict) -> str:
    return e.get("source_id") or e.get("source_name") or e.get("source_url", "")


def build_trends(topic: str, conf: c.Config, now: datetime) -> list[dict]:
    by_tag: dict[str, list[dict]] = defaultdict(list)
    for e in entries_for_topic(topic):
        for tag in e.get("tags") or []:
            by_tag[tag.lower()].append(e)

    trends = []
    for tag, members in by_tag.items():
        sources = {source_key(m) for m in members}
        if len(members) < MIN_MEMBERS or len(sources) < MIN_SOURCES:
            continue
        fresh = [m for m in members if c.is_fresh(m, conf.max_age_days, now=now)]
        dates = [c.best_date(m) for m in members if c.best_date(m)]
        momentum = round(len(fresh) * RECENT_WEIGHT + (len(members) - len(fresh)), 1)
        trends.append(
            {
                "topic": topic,
                "tag": tag,
                "count": len(members),
                "recent": len(fresh),
                "sources": len(sources),
                "momentum": momentum,
                "first_seen": min(dates) if dates else None,
                "last_seen": max(dates) if dates else None,
                "members": [
                    {
                        "title": m.get("title"),
                        "url": m.get("source_url"),
                        "date": c.best_date(m),
                        "fresh": c.is_fresh(m, conf.max_age_days, now=now),
                    }
                    for m in sorted(members, key=lambda x: (c.best_date(x) or ""), reverse=True)
                ],
            }
        )
    trends.sort(key=lambda t: (-t["momentum"], -t["count"]))
    return trends


def render_md(all_trends: dict[str, list[dict]], now: str) -> str:
    out = [
        "# 📈 Emerging Trends",
        "",
        f"> Rising themes per topic, clustered from tagged findings (live + recent "
        f"archive). Updated {now}. A theme needs ≥{MIN_MEMBERS} findings from "
        f"≥{MIN_SOURCES} sources; **recent activity is weighted highest**.",
        "",
    ]
    for topic, meta in c.TOPICS.items():
        trends = all_trends.get(topic, [])
        out += [f"## {meta['name']}", ""]
        if not trends:
            out += ["_No emerging theme has crossed the threshold yet — needs more volume._", ""]
            continue
        for t in trends:
            arrow = "🔺" if t["recent"] else "▪️"
            out.append(
                f"### {arrow} {t['tag']}  ·  {t['count']} findings "
                f"({t['recent']} recent) · {t['sources']} sources · "
                f"momentum {t['momentum']}"
            )
            if t["first_seen"]:
                out.append(f"_First seen {t['first_seen']} · latest {t['last_seen']}._")
            out.append("")
            for m in t["members"][:6]:
                tag = " · _latest_" if m["fresh"] else ""
                out.append(f"- [{m['title']}]({m['url']}) ({m['date']}){tag}")
            out.append("")
    out += ["---", "", f"<sub>Generated by scripts/trends.py on {now}.</sub>", ""]
    return "\n".join(out)


def main() -> int:
    conf = c.load_config()
    now_dt = datetime.now(UTC)
    now = now_dt.strftime("%Y-%m-%d")
    all_trends = {t: build_trends(t, conf, now_dt) for t in c.TOPICS}
    c.save_json(c.DATA_DIR / "trends.json", all_trends)
    (c.ROOT / "TRENDS.md").write_text(render_md(all_trends, now), encoding="utf-8")
    total = sum(len(v) for v in all_trends.values())
    print(f"Detected {total} trend(s) across {len(c.TOPICS)} topics -> TRENDS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
